/* Even Fibonacci numbers
 * Problem 002
 *
 * Each new tern in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main() {
  int f1 = 1, f2 = 2, f3 = f1 + f2;
  unsigned long long sum = 2;
  while (f3 < 4000000) {
    f1 = f2;
    f2 = f3;
    if (f3 % 2 == 0)
      sum += f3;
    f3 = f1 + f2;
  }
  printf("%llu\n", sum);
  return 0;
}
