/* Pentagon numbers.
 * Problem 044
 *
 * Pentagonal numbers are generated by the formula Pn = n(3n - 1) / 2. The
 * first ten pentagonal numbers are:
 *
 *   1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 *   It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 *   70 - 22 = 48, is not a pentagonal.
 *
 *   Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 *   difference are pentagonal and D = |Pk - Pj| is minimised; what is the value
 *   of D?
 */

#include <stdlib.h>
#include <stdio.h>

// First 10k pentagonal numbers (max ~ 10^8)
#define N 10000

int binsearch(unsigned int x, unsigned int P[], int left, int right) {
  if (right < left)
    return 0;
  int mid = left + (right - left) / 2;
  if (x < P[mid])
    return binsearch(x, P, left, mid-1);
  else if (x > P[mid])
    return binsearch(x, P, mid+1, right);
  else
    return mid;
}

int main() {
  // Compute first N pentagonal numbers
  unsigned int P[N] = { 0 }, n, m, s, d, j, k;
  for (n = 1; n <= N; ++n)
    P[n-1] = n * (3 * n - 1) / 2;
  // Check all pairs of numbers in P
  for (j = 0; j < N; ++j) {
    for (k = j + 1; k < N; ++k) {
      s = P[j] + P[k];
      if (s < P[k+1]) {
        ++j;
        k = j;
      }
      else if (n = binsearch(s, P, 0, N-1)) {
        d = P[k] - P[j];
        if (m = binsearch(d, P, 0, N-1)) {
          printf("P%d, P%d; sum = %d = P%d, diff = %d = P%d\n", j, k,
              s, n, d, m);
          return 0;
        }
      }
    }
  }
  return 0;
}
