#!/usr/bin/env python

"""
Triangular, pentagonal, and hexagonal.
Problem 045

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

  Triangle    Tn = n(n + 1) / 2     1, 3, 6, 10, 15, ...
  Pentagonal  Pn = n(3n - 1) / 2    1, 5, 12, 22, 35, ...
  Hexagonal   Hn = n(2n - 1)        1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

h = 143
p = 166
t = 286
H = h * (2 * h - 1)
P = p * (3 * p - 1) // 2
T = t * (t + 1) // 2
while T != P or P != H:
  h += 1
  H = h * (2 * h - 1)
  while P < H:
    p += 1
    P = p * (3 * p - 1) // 2
  while T < P:
    t += 1
    T = t * (t + 1) // 2
print("T{} = P{} = H{} = {}".format(t, p, h, H))
